//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenBay()
        {
            this.Ghe_ChuyenBay = new HashSet<Ghe_ChuyenBay>();
        }
    
        public int maCB { get; set; }
        public Nullable<System.DateTime> ngayGioDi { get; set; }
        public Nullable<int> thoiGianBay { get; set; }
        public byte tienTrinhID { get; set; }
        public Nullable<int> maTB { get; set; }
    
        public virtual TuyenBay TuyenBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ghe_ChuyenBay> Ghe_ChuyenBay { get; set; }
        public virtual TienTrinh TienTrinh { get; set; }
    }
}
