//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferObject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightManagementContext : DbContext
    {
        public FlightManagementContext()
            : base("name=FlightManagementContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<ChuyenBay> ChuyenBays { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<Ghe_ChuyenBay> Ghe_ChuyenBay { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiMayBay> LoaiMayBays { get; set; }
        public virtual DbSet<MayBay> MayBays { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<QuyDinh> QuyDinhs { get; set; }
        public virtual DbSet<SanBay> SanBays { get; set; }
        public virtual DbSet<SanBayTrungGian> SanBayTrungGians { get; set; }
        public virtual DbSet<TienTrinh> TienTrinhs { get; set; }
        public virtual DbSet<TuyenBay> TuyenBays { get; set; }
        public virtual DbSet<VeChuyenBay> VeChuyenBays { get; set; }
    }
}
