//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ghe()
        {
            this.Ghe_ChuyenBay = new HashSet<Ghe_ChuyenBay>();
        }
    
        public int maGhe { get; set; }
        public string tenGhe { get; set; }
        public string hangGhe { get; set; }
        public Nullable<int> maMB { get; set; }
        public Nullable<double> tileGia { get; set; }
    
        public virtual MayBay MayBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ghe_ChuyenBay> Ghe_ChuyenBay { get; set; }
    }
}
