//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe_ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ghe_ChuyenBay()
        {
            this.VeChuyenBays = new HashSet<VeChuyenBay>();
        }
    
        public int maGhe { get; set; }
        public int maCB { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public Nullable<double> gia { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        public virtual Ghe Ghe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeChuyenBay> VeChuyenBays { get; set; }
    }
}
