//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinh
    {
        public int maQD { get; set; }
        public string tenQD { get; set; }
        public string noidungQD { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
    }
}
