//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanBayTrungGian
    {
        public int maSB { get; set; }
        public int maTB { get; set; }
        public Nullable<System.TimeSpan> thoiGianDung { get; set; }
    
        public virtual SanBay SanBay { get; set; }
        public virtual TuyenBay TuyenBay { get; set; }
    }
}
